services:
  web:
    image: nginx
    ports:
      - "51:80"
    volumes:
      - "/home/azzafh/site:/usr/share/nginx/html"
    restart: always
  mongo-demo:
    image: mongo:latest
    container_name: mongo-demo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: azza
    ports:
      - "27017:27017"
    restart: always
  
